name       : cpu-x
version    : 4.0.1
release    : 6
source     :
    - https://github.com/X0rg/CPU-X/archive/v4.0.1.tar.gz : c41fbb3000e3e6f79e5228aa0237fde4f98b11df8ccb4c9a46f7e63a4a7011bf
license    : GPL-3.0-or-later
component  : system.utils
homepage   : https://x0rg.github.io/CPU-X/
summary    : Gathers information on CPU, motherboard and more
description: |
    CPU-X is a Free software that gathers information on CPU, motherboard and more.
    CPU-X is similar to CPU-Z, but CPU-X is a Free and Open Source software designed for GNU/Linux; also, it works on *BSD.
    It can be used in graphical mode by using GTK or in text-based mode by using NCurses. A dump mode is present from command line.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcpuid)
    - pkgconfig(libpci)
    - pkgconfig(libprocps)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
