name       : cpu-x
version    : 3.2.3
release    : 1
source     :
    - https://github.com/X0rg/CPU-X/archive/v3.2.3.tar.gz : 4c11b3e3632870e9af81c5c0fa642edff8dd4622a172bbb788c4e6be595eb014
license    : GPL-3.0-or-later
component  : system.utils
summary    : CPU-X is a Free software that gathers information on CPU, motherboard and more
description: |
    CPU-X is a Free software that gathers information on CPU, motherboard and more.
    CPU-X is similar to CPU-Z, but CPU-X is a Free and Open Source software designed for GNU/Linux; also, it works on *BSD.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcpuid)
    - pkgconfig(libpci)
    - pkgconfig(libprocps)
    - nasm
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
