name       : cpu-x
version    : 3.2.4
release    : 2
source     :
    - https://github.com/X0rg/CPU-X/archive/v3.2.4.tar.gz : f266388e13c527a5d1d98ec70957b1284f67aa89470cf71bc98ecb41c21542eb
license    : GPL-3.0-or-later
component  : system.utils
summary    : CPU-X is a Free software that gathers information on CPU, motherboard and more
description: |
    CPU-X is a Free software that gathers information on CPU, motherboard and more.
    CPU-X is similar to CPU-Z, but CPU-X is a Free and Open Source software designed for GNU/Linux; also, it works on *BSD.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcpuid)
    - pkgconfig(libpci)
    - pkgconfig(libprocps)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
