name       : cpu-x
version    : 4.1.0
release    : 7
source     :
    - https://github.com/X0rg/CPU-X/archive/v4.1.0.tar.gz : b7f3158b226badec77500a8f847850b618a167d7b9e6599a145c53e31df64b0a
license    : GPL-3.0-or-later
component  : system.utils
homepage   : https://x0rg.github.io/CPU-X/
summary    : Gathers information on CPU, motherboard and more
description: |
    CPU-X is a Free software that gathers information on CPU, motherboard and more.
    CPU-X is similar to CPU-Z, but CPU-X is a Free and Open Source software designed for GNU/Linux; also, it works on *BSD.
    It can be used in graphical mode by using GTK or in text-based mode by using NCurses. A dump mode is present from command line.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcpuid)
    - pkgconfig(libpci)
    - pkgconfig(libprocps)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
