name       : cpu-x
version    : 4.0.0
release    : 3
source     :
    - https://github.com/X0rg/CPU-X/archive/v4.0.0.tar.gz : 01deaa34f9fef5e6b5783cf7c633621b56374edc3ece0608a1b80e1a5435cf4c
license    : GPL-3.0-or-later
component  : system.utils
homepage   : https://x0rg.github.io/CPU-X/
summary    : Gathers information on CPU, motherboard and more
description: |
    CPU-X is a Free software that gathers information on CPU, motherboard and more.
    CPU-X is similar to CPU-Z, but CPU-X is a Free and Open Source software designed for GNU/Linux; also, it works on *BSD.
    It can be used in graphical mode by using GTK or in text-based mode by using NCurses. A dump mode is present from command line.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcpuid)
    - pkgconfig(libpci)
    - pkgconfig(libprocps)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
