name       : cpu-x
version    : 4.5.1
release    : 13
source     :
    - https://github.com/X0rg/CPU-X/archive/refs/tags/v4.5.1.tar.gz : 1d36693a396ea337b174b8eef4820390491c65382bb5b85a0358feb858863d39
license    : GPL-3.0-or-later
component  : system.utils
homepage   : https://x0rg.github.io/CPU-X/
summary    : Gathers information on CPU, motherboard and more
description: |
    CPU-X is a Free software that gathers information on CPU, motherboard and more.
    CPU-X is similar to CPU-Z, but CPU-X is a Free and Open Source software designed for GNU/Linux; also, it works on *BSD.
    It can be used in graphical mode by using GTK or in text-based mode by using NCurses. A dump mode is present from command line.
builddeps  :
    - pkgconfig(OpenCL)
    - pkgconfig(glfw3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcpuid)
    - pkgconfig(libpci)
    - pkgconfig(libprocps)
    - pkgconfig(vulkan)
    - vulkan-headers
setup      : |
    %cmake_ninja -DGSETTINGS_LOCALINSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
